// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsApi.Contexts;

namespace StudentsApi.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    partial class StudentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentsApi.Entities.GroupEntity", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherEntityTeacherId")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("TeacherEntityTeacherId");

                    b.ToTable("GroupEntity");
                });

            modelBuilder.Entity("StudentsApi.Entities.StudentEntity", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvrScore")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("StudentEntity");
                });

            modelBuilder.Entity("StudentsApi.Entities.TeacherEntity", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discipline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupEntityGroupId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.HasIndex("GroupEntityGroupId");

                    b.ToTable("TeacherEntity");
                });

            modelBuilder.Entity("StudentsApi.Entities.GroupEntity", b =>
                {
                    b.HasOne("StudentsApi.Entities.TeacherEntity", null)
                        .WithMany("Groups")
                        .HasForeignKey("TeacherEntityTeacherId");
                });

            modelBuilder.Entity("StudentsApi.Entities.StudentEntity", b =>
                {
                    b.HasOne("StudentsApi.Entities.GroupEntity", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("StudentsApi.Entities.TeacherEntity", b =>
                {
                    b.HasOne("StudentsApi.Entities.GroupEntity", null)
                        .WithMany("Teachers")
                        .HasForeignKey("GroupEntityGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
