name: Build and Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore CoreWebApi.sln

    - name: Build solution
      run: dotnet build CoreWebApi.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test CoreWebApi.sln --configuration Release --no-build --verbosity normal
